### ISSUE TITLE
current status and adaptation for selvatic in south america

### ISSUE THREAD

**Issue by mckaygerhard** [DokimiCU/aotearoa#3]
hi i m checked your work and want to ask for current progress..  i want to integrated in the current most played server .. the VenenuX subnasa https://codeberg.org/minenux (currently to paly get to http://subs.fusilsystem.com )

my idea is to emulated the south amereica most hard dangerous biome (that is full of large trees and  tangle-branched thorny plants)

the problem is that thismod work s good only with mg_valley and for the tepuys the most ancient rocks of the world i need island of v7 mapgen and large mountains adapted.. 
the second and more important problem is that i need to know the progress of the project.. and how can i help to modify for my needs

thanks in advance .. cos i not a coder of minetest in really..

**Comment by DokimiCU** [comment]
This mod is not maintained now.

Sounds like you'd be creating an entire new mod, rather than adapting this one. Of course, you can use the textures and code to help.

**Comment by mckaygerhard** [comment]
@DokimiCU 

> This mod is not maintained now.

sorry to read that! it seems a great mod.. and i was made some fixeds.. still not reported here due lack of time.. but now i dont know if i must report or not due your response..
 
> Sounds like you'd be creating an entire new mod, rather than adapting this one. Of course, you can use the textures and code to help.

i just can parse the artwork without any problem of redistribution?

**Comment by DokimiCU** [comment]
I still like this mod :-)  
But maintaining this is very low priority for me.

Bug fixes:
- You could make a fork and add your fixes there
- You could post on the forums topic [https://forum.minetest.net/viewtopic.php?f=9&t=20770&hilit=Aotearoa](url) e.g. with a link to your fixed version.

Many people liked this mod, so maybe someone else might take over maintaining it (someone almost did, but then dropped it).

For your project:
All licenses are open source (see readme). As long as your project is also open source and gives credit that's okay. Hope that helps.

**Comment by mckaygerhard** [comment]
> Many people liked this mod, so maybe someone else might take over maintaining it (someone almost did, but then dropped it).
> 
> For your project: All licenses are open source (see readme). As long as your project is also open source and gives credit that's okay. Hope that helps.

i am using it.. so i will try to upload and post later here the experience.. let me prepare some things and in one month i will post feedback here.. 

> I still like this mod :-) But maintaining this is very low priority for me.

i wil try

>     * You could make a fork and add your fixes there
sending PR ?

>     * You could post on the forums topic [https://forum.minetest.net/viewtopic.php?f=9&t=20770&hilit=Aotearoa](url) e.g. with a link to your fixed version.

i do not use forum neither discordshit.. too much people dump

**Comment by DokimiCU** [comment]
This mod is not maintained. I will not respond to pull requests. I am unlikely to look at the work you do. I am too busy.

If you want to share your work, then the forums are the place to go. I know forums are imperfect, but no one will see it here. :-)

**Comment by mckaygerhard** [comment]
ok understood now.. i noted the #4  opened.. so i will fork this mod and later post here and there the new url... thanks for your effors..
